apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service-app
  labels:
    app: task-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-service-app
  template:
    metadata:
      labels:
        app: task-service-app
    spec:
      containers:
        - name: task-service
          image: 030511553020.dkr.ecr.us-east-1.amazonaws.com/task-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
