apiVersion: v1
kind: Service
metadata:
  name: task-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: task-service-app
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090