apiVersion: v1
kind: Service
metadata:
  name: task-service-svc
  labels:
    run: task-service
spec:
  ports:
      - port: 9090
        targetPort: 9090
        protocol: TCP
  selector:
    app: task-service-app